import base64
import time
import os
import logging
import requests
from flask import Flask, render_template, request
from pymongo import MongoClient
from dotenv import load_dotenv


# db credentials are waiting for the application in .env file generated by Vault Agent
while True:
    try:
        load_dotenv(dotenv_path='/app/secrets/.env')
        DB_USERNAME = os.environ['DB_USERNAME']
        DB_PASSWORD = os.environ['DB_PASSWORD']
    except Exception:
        print("Could not load credentials from .env file\nRetrying...\n")
        time.sleep(5)
    else:
        break


print(f'''
THIS IS FOR DEMONSTRATION PURPOSES
DB username is {DB_USERNAME}
DB password is {DB_PASSWORD}
''')

app = Flask(__name__)

log = logging.getLogger('werkzeug')
log.setLevel(logging.ERROR)

client = MongoClient('database-mongodb', 27017, username=DB_USERNAME,
                        password=DB_PASSWORD, authSource='my_database')
db = client.my_database
users = db.users

@app.route('/')
@app.route('/register', methods =['GET', 'POST'])
def register():
    msg = ''
    if request.method == 'POST' and 'FirstName' in request.form \
                            and 'LastName' in request.form and 'CreditCard' in request.form:

        first_name = request.form['FirstName']
        last_name = request.form['LastName']
        credit_card = request.form['CreditCard']

        credit_card_bytes = credit_card.encode("ascii")
        b64_bytes = base64.b64encode(credit_card_bytes)
        b64_string = b64_bytes.decode("ascii")

        # NOTICE - localhost, no auth token
        encryption_res = requests.post('http://localhost:8200/v1/transit/encrypt/my-key',
                                        data={"plaintext": b64_string})
        cipher = encryption_res.json()["data"]["ciphertext"]

        users.insert_one({"FirstName": first_name, "LastName": last_name, "CreditCard": cipher})

        msg = 'You have successfully registered!'

    elif request.method == 'POST':
        msg = 'Please fill out the form'

    return render_template('register.html', msg = msg)
