name: Create deploy on release

on:
  push:
    tags: [ '*.*.*' ]

env:
  NEW_TAG: ${{ github.ref_name }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        ref: 'main'
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: raakatz
        password: ${{ secrets.DOCKER_HUB }}
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: raakatz/flask-vault
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.3.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
  
  update_kustomization_webapp:
    name: Update kustomization for webapp to trigger Canary
    runs-on: ubuntu-latest
    needs:
    - push_to_registry
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      with:
        repository: 'raakatz/gitops-flagger'
        ref: 'main'
        token: ${{ secrets.GH_PAT }}
    
    - name: yq - portable yaml processor
      uses: mikefarah/yq@v4.30.8
      with:
        cmd: yq -i '.images[0].newTag = "${{ env.NEW_TAG }}"' './apps/webapp/kustomization.yaml'

    - name: git push
      run: |
        git config --global user.name "Raanan"
        git config --global user.email "raakatz97@gmail.com"
        git add apps/webapp/kustomization.yaml
        git commit -m "pushed by github actions for ${{ env.NEW_TAG }}"
        git push
